### ISSUE TITLE
Error: Call to undefined method Magento\SharedCatalog\Model\CustomerGroupManagement::isMasterCatalogAvailable()  in Magento 2.4.2

### ISSUE THREAD

**Issue by pusachev** [Smile-SA/magento2-module-elasticsuite-shared-catalog#7]
**isMasterCatalogAvailable()** method unavailable in Magento 2.4.2

**Preconditions**

- elasticsearch:7.6
- php-fpm:7.4
- nginx
- mysql:8.0
- 

**Magento Version** : 2.4.2

**ElasticSuite Version** : 2.10.3

**Environment** : developer

**Third party modules** : not used

**Steps to reproduce**

- Go to the product category page

**Expected result**

- observe products

**Actual result**

- observe PHP notice

![image](https://user-images.githubusercontent.com/17767002/106436409-b9bfa900-647c-11eb-8676-8aaeec1a3f24.png)

**Comment by ChrHartwig** [comment]
Same here. 

isMasterCatalogAvailable() does not exist in Magento Commerce 2.4.2 anymore.

**Comment by prapraj** [comment]
Magento 2.4.2 class Magento\SharedCatalog\Model\CustomerGroupManagement has renamed method isMasterCatalogAvailable() to isPrimaryCatalogAvailable(). So it would be great if it is fixed from the repository, rather than having to override it into local code

**Comment by jmonrove** [comment]
the suggestion by @prapraj fixed this error.
The file affected is vendor/smile/module-elasticsuite-shared-catalog/Plugin/Catalog/Model/ResourceModel/Product/Fulltext/CollectionPlugin.php
line 136
![image](https://user-images.githubusercontent.com/32687858/117330873-fbc90400-ae4a-11eb-8561-afc128b5ef16.png)

**Comment by romainruaud** [comment]
@vahonc can you look at this one ? You'll need a Magento B2B environment.

The proposed solution in #9 is a good start but we cannot just change the method that is used, we need something that could work with the different Magento versions.

Regards

**Comment by vahonc** [comment]
OKay, I'll take care of it.

BR,
Vadym

**Comment by vahonc** [comment]
I've added PR [#10](https://github.com/Smile-SA/magento2-module-elasticsuite-shared-catalog/pull/10) for this one.

**Comment by alinolandry** [comment]
@romainruaud  I had the same problem, I continue to wait merge of PR #10  and last update of Smile_ElasticsuiteSharedCatalog module.

**Comment by romainruaud** [comment]
Fixed by #10 and published in 2.10.2 minor

**Comment by alinolandry** [comment]
Thank you @romainruaud , Now I can remove my magento patch and make update to 2.10.2, thank you

**Comment by samc2810** [comment]
Hi Guys
@romainruaud been waiting for this too for a while ;)

BTW the new Tag didnt add the changes yet so its still not working.
https://github.com/Smile-SA/magento2-module-elasticsuite-shared-catalog/blob/2.10.2/Plugin/Catalog/Model/ResourceModel/Product/Fulltext/CollectionPlugin.php#L136
vs 
https://github.com/Smile-SA/magento2-module-elasticsuite-shared-catalog/blob/2.10.x/Plugin/Catalog/Model/ResourceModel/Product/Fulltext/CollectionPlugin.php#L137
![image](https://user-images.githubusercontent.com/1092318/122945020-8f618000-d378-11eb-85a5-7b49001fb71b.png)

![image](https://user-images.githubusercontent.com/1092318/122945078-99837e80-d378-11eb-9b23-13efd70384b6.png)

Thanks and cheers 
Sam

**Comment by romainruaud** [comment]
Woops... my bad, I tagged master instead of 2.10.x branch...

I'll remove the tag and redo it properly, please cleanup composer cache prior updating

**Comment by romainruaud** [comment]
Should be ok right now
